name: "Habeebs Simple Greeting Action"
description: A Custom GitHub Action to print a greeting message

inputs:
  username: 
    description: "Name of user to greet"
    required: true
  season:
    description: "Name of season"
    required: false
    default: Summer

outputs:  #we use outputs whenever we want to use a variable created and stored in $GITHUB_OUTPUT in another job, we need this because we are using it outside the created step
  message:
    description: "Generated greeting message"
    value: ${{ steps.greet.outputs.message }}

runs:
  using: "composite"
  steps:
    - name: Print greeting
      id: greet
      shell: bash
      run: |
        echo "Hello ${{ inputs.username }}, welcome to ${{ inputs.season }} season."
        echo "message=Hello ${{ inputs.username }}" >> $GITHUB_OUTPUT  
    #GITHUB_OUTPUT file stores variables with values in it, you get the output using steps.<IDofStepOutputwasCreated>.outputs.<VariableKey> 
    #message is the variable key here.
